services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: lottery
      POSTGRES_USER: lottery
      POSTGRES_PASSWORD: lottery
    ports:
      - 5438:5432
    expose:
      - "5438"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U lottery"]
      interval: 5s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7-alpine
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
    expose:
      - "6380"
    ports:
      - 6380:6379

volumes:
  pgdata: